In [3]:
# Downloading tinyshakesphere for training
!curl https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt > tinyshakespeare.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1089k  100 1089k    0     0   354k      0  0:00:03  0:00:03 --:--:--  354k


# 1. Inspecting the tinyshakespeare text file for training

In [2]:
# Inspecting the text file
with open('tinyshakespeare.txt','r') as file:
    text = file.read()

In [3]:
print(f'There are {len(text)} characters in the dataset')

There are 1115394 characters in the dataset


In [4]:
# Printing the first 1000 characters
print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [5]:
# Identifying the number of unique characters contained in the text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(f"Number of unique characters (including white space): {vocab_size}{''.join(chars)}")

Number of unique characters (including white space): 65
 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


# 2. Basic mapping between characters to integers

More sophisticated examples include Google's SentencePiece and OpenAI's tiktoken

In [6]:
# Assigning numbers to each characters to encode the characters to integers
ctoi = {char : num for num, char in enumerate(chars)}
encode = lambda s: [ctoi[c] for c in s]
print(encode('Shakespeare in digits'))

# Reversely, decode integers back to characters
itoc = {num : char for num, char in enumerate(chars)}
decode = lambda l : ''.join([itoc[i] for i in l])
print(decode(encode('Shakespeare in digits')))

[31, 46, 39, 49, 43, 57, 54, 43, 39, 56, 43, 1, 47, 52, 1, 42, 47, 45, 47, 58, 57]
Shakespeare in digits


In [7]:
# Tokenizing the total text. Adapted the code to work with Tensorflow instead of pytorch
import tensorflow as tf
data = tf.convert_to_tensor(encode(text))
print(data.shape, data.dtype)
print(data[:100])

2024-07-26 22:09:20.256514: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-26 22:09:20.835429: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-26 22:09:22.752208: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


(1115394,) <dtype: 'int32'>
tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59], shape=(100,), dtype=int32)


In [8]:
# Train and validation split sets, with 9:1 ratio
n = int(0.9*len(data))
data_train = data[:n]
data_test = data[n:]
print(f'Length of train data : {len(data_train)}\nLength of test data : {len(data_test)}')

Length of train data : 1003854
Length of test data : 111540


In [9]:
# Starting with block_size implementation
block_size = 8
print(data_train[:block_size + 1])
x = data_train[:block_size]
y = data_train[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f'Input : {context}, Output : {target}')

tf.Tensor([18 47 56 57 58  1 15 47 58], shape=(9,), dtype=int32)
Input : [18], Output : 47
Input : [18 47], Output : 56
Input : [18 47 56], Output : 57
Input : [18 47 56 57], Output : 58
Input : [18 47 56 57 58], Output : 1
Input : [18 47 56 57 58  1], Output : 15
Input : [18 47 56 57 58  1 15], Output : 47
Input : [18 47 56 57 58  1 15 47], Output : 58


In [10]:
## To be worked on : packaging the code with script with variables for later
# Depiction of the chunk(or in here, block)-wise transformation.
# Having varied blocksize allows the algorithm to take into account the context for inference purpose



tf.random.set_seed(1337) # To be sure to have consistent random number
batch_size = 4 # The number of independent sequences to train in parallel
block_size = 8 # The maximum context length for prediction

def get_batch(split):
    data = data_train if split == 'train' else data_test
    # Retrieving batches randomly
    ix = tf.random.uniform(shape = (batch_size,),
                           maxval = len(data) - block_size,
                           dtype = tf.int32)
    # Stacking the list of tensors
    x = tf.stack([data[i:i+block_size] for i in ix])
    y = tf.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print(xb)
print(yb)
for batch in range(batch_size):
    for block in range(block_size):
        context = xb[batch, :block+1]
        target = yb[batch, block]
        print(f'When input is {context.numpy().tolist()} the target is {target}')

tf.Tensor(
[[ 1 51 63  1 41 53 39 58]
 [39 42  0 20 47 57  1 52]
 [32 53  1 56 43 60 43 50]
 [54 39 52 63  1 54 47 43]], shape=(4, 8), dtype=int32)
tf.Tensor(
[[51 63  1 41 53 39 58  6]
 [42  0 20 47 57  1 52 39]
 [53  1 56 43 60 43 50  1]
 [39 52 63  1 54 47 43 41]], shape=(4, 8), dtype=int32)
When input is [1] the target is 51
When input is [1, 51] the target is 63
When input is [1, 51, 63] the target is 1
When input is [1, 51, 63, 1] the target is 41
When input is [1, 51, 63, 1, 41] the target is 53
When input is [1, 51, 63, 1, 41, 53] the target is 39
When input is [1, 51, 63, 1, 41, 53, 39] the target is 58
When input is [1, 51, 63, 1, 41, 53, 39, 58] the target is 6
When input is [39] the target is 42
When input is [39, 42] the target is 0
When input is [39, 42, 0] the target is 20
When input is [39, 42, 0, 20] the target is 47
When input is [39, 42, 0, 20, 47] the target is 57
When input is [39, 42, 0, 20, 47, 57] the target is 1
When input is [39, 42, 0, 20, 47, 57, 1] the targ

In [11]:
eval_iters = 200

# A function to average up the loss in multiple batches for both splits
# @tf.function : removing the code, despite slower performance as it causes an error
def estimate_loss():
    output = {}
    model.trainable = False # Setting the model to evaluation phase
    for split in ['train','val']:
        losses = []
        for _ in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model.call(X,Y)
            losses.append(loss)
        output[split] = tf.reduce_mean(losses)
    model.trainable = True # Setting the model back to training phase
    return output

In [12]:
tf.random.set_seed(1337)

class BigramLanguageModel(tf.keras.Model):

    def __init__(self, vocab_size):
        '''Initializing embedding layer, which maps integer indices to
        dense vectors of vocab size'''
        super(BigramLanguageModel, self).__init__()
        self.token_embedding_table = tf.keras.layers.Embedding(vocab_size, vocab_size)

    def call(self, idx, targets=None):
        '''Method for loss calculation, based on idx (input token indices) and
        target (target token indices)
        B : Batch size
        T : Time = sequence length = block size
        C : Channel = number of classes = vocab size
        '''
        logits = self.token_embedding_table(idx)  # Replacing embedding to the indices

        if targets is None:
            loss = None
        else:
            # Reshaping the tensor so that it's compatible with categorical cross entropy
            B, T, C = tf.shape(logits) # Get the shape of logits
            logits = tf.reshape(logits, (B * T, C)) # Flatten logits for comparison
            targets = tf.reshape(targets, (B * T,)) # Flatten targets
            loss = tf.reduce_mean(tf.keras.losses.sparse_categorical_crossentropy(targets, logits, from_logits=True))
        return logits, loss

    def generate(self, idx, max_new_tokens):
        '''
        Text generating method
        '''
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :]  # becomes (B, C)
            # apply softmax to get probabilities
            probs = tf.nn.softmax(logits, axis=-1)  # (B, C)
            # sample prediction from the distribution
            idx_next = tf.random.categorical(tf.math.log(probs), num_samples=1, dtype=tf.int64)

#            idx_next = tf.random.categorical(probs, num_samples=1)  # (B, 1)
            # append sampled index to the running sequence
            idx = tf.concat([idx, tf.cast(idx_next, tf.int32)], axis=1)  # (B, T+1)
        return idx

model = BigramLanguageModel(vocab_size)
logits, loss = model.call(xb, yb)
print(logits.shape)
print(loss.numpy())

print(decode(model.generate(idx=tf.zeros((1, 1), dtype=tf.int32), max_new_tokens=100)[0].numpy().tolist()))

(32, 65)
4.174439

sZTe-Wz-K-?hNl?Yr:r'KUFLHH:QlLbpCkI
oYwnqePrE
!zgz'T3,?ZhzxEjItfpzARjGjM&vv.;OBdqElQ qwcwcfwWhPKs:$'


In [13]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate = 0.001)

In [14]:
batch_size = 32
for step in tf.range(4000):
    if step % eval_iters == 0:
        losses = estimate_loss()
        print(f"Step {step}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # Sample a batch of data
    xb, yb = get_batch('train')

    # Evaluate the loss
    with tf.GradientTape() as tape:
        logits, loss = model(xb,yb)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

print(f'Final Loss: {loss.numpy()}')

Step 0: train loss 4.1713, val loss 4.1711
Step 200: train loss 3.7201, val loss 3.7239
Step 400: train loss 3.3985, val loss 3.4094
Step 600: train loss 3.1741, val loss 3.1845
Step 800: train loss 3.0110, val loss 3.0250
Step 1000: train loss 2.8861, val loss 2.9014
Step 1200: train loss 2.8002, val loss 2.8108
Step 1400: train loss 2.7378, val loss 2.7468
Step 1600: train loss 2.6697, val loss 2.6898
Step 1800: train loss 2.6504, val loss 2.6521
Step 2000: train loss 2.6072, val loss 2.6195
Step 2200: train loss 2.5896, val loss 2.6056
Step 2400: train loss 2.5700, val loss 2.5762
Step 2600: train loss 2.5507, val loss 2.5637
Step 2800: train loss 2.5499, val loss 2.5518
Step 3000: train loss 2.5290, val loss 2.5375
Step 3200: train loss 2.5274, val loss 2.5421
Step 3400: train loss 2.5146, val loss 2.5199
Step 3600: train loss 2.4991, val loss 2.5186
Step 3800: train loss 2.4988, val loss 2.5146
Final Loss: 2.507786273956299


In [15]:
# Generate a sequence
idx = tf.zeros((1, 1), dtype=tf.int32)
generated_sequence = model.generate(idx, max_new_tokens=1000).numpy()
print(decode(generated_sequence[0].tolist()))



Fatin wivor thiranen as hy psce lf tes: tangeismershert ma forerdve wilite
GHoprs be uelatheItit Ingrinme ll llou ond aglod
edeath
D bloouGnow; sh he l la njJxKeet;EMy yoeke fo t LLjnon
FR-Whooul tollouth
I n vesere his.

I dg
Weronth tournd woour ariets iend t I bist p'CKy: s d! ms les titowil, irchatigherou
Buo may;? be larke mayomy

Th d moweshest htover h ht wll anl Warthenour,

ALAn ver?

The
D: to
HAUSthe.!


TAkey stan fof, b, t w,
TULLOy mit amad
DYI whaf she she.
SAPEO:
CKIOMOx;
CEOTEd t ace ben?
aree t thapoush, tes flyofen pea
Thare is-fe wau, f way s, pend!ME d ik; as ist theawharevers:
Wherof nt; tey, d t hy?Hoomathice te oKEDWha as ipp arre he n n



We,
NECES:

GDorpremot y rcldd icucRORDEur YK:
D t un lled d a?
oue IVAseaiso'?
P;Juny th sel'ty tleandw
CUENSLoughthedked and withes ousthad besthind w st s wrmomy, toxthe
Dzgg apon
DI mbe, bilorey f ws he wve, manoory urswicay.
Mous se he tcetheayI M---g.
Thes

HAn hedwed sthadr the ind, tou fo erthicacoforil woqut thavea

### The mathematical trick self-attention

In [19]:
# Tokens learning from previous context, calculating average of all to previous tokens
B,T,C = 4,8,2
x = tf.random.uniform(shape=(B, T,C))

xbow = tf.zeros((B,T,C)) # Defining a bag of words
for b in range (B):
    for t in range (T):
        xprev = x[b, :t+1] # Batch, including the tth token
        xbow = xbow.numpy()  # Convert xbow to numpy array to support assignment
        xbow[b, t] = tf.reduce_mean(xprev, axis=0).numpy()  # Calculate mean and assign to xbow
        xbow = tf.convert_to_tensor(xbow)  # Convert back to tensor

### Vectorizing the above function

In [20]:
w = tf.linalg.band_part(tf.ones((T,T)),num_lower = 8, num_upper= 0) # Calculating weights with matrix
w = w / tf.math.reduce_sum(w, axis = 1, keepdims = True)

xbow2 = w @ x

tf.experimental.numpy.allclose(xbow,xbow2).numpy()

True

In [29]:
# version 3: use Softmax
tril = tf.linalg.band_part(tf.ones((T,T)),num_lower = 8, num_upper= 0)
w = tf.zeros((T,T))
w = tf.where(tril == 0, float('-inf'), w) # Indicating future bow cannot communicate with the past
w = tf.nn.softmax(w, axis = -1) # normalizing the weight matrix
xbow3 = w @ x
tf.experimental.numpy.allclose(xbow,xbow3).numpy()

True

### Modifying the model

In [32]:
tf.random.set_seed(1337)
n_embed = 32

class BigramLanguageModel(tf.keras.Model):

    def __init__(self, vocab_size):
        '''Initializing embedding layer, which maps integer indices to
        dense vectors of vocab size'''
        super(BigramLanguageModel, self).__init__()
        self.token_embedding_table = tf.keras.layers.Embedding(vocab_size, n_embed)
        self.lm_head = tf.keras.layers.Dense(units=vocab_size)

    def call(self, idx, targets=None):
        '''Method for loss calculation, based on idx (input token indices) and
        target (target token indices)
        B : Batch size
        T : Time = sequence length = block size
        C : Channel = number of classes = vocab size
        '''
        token_emb = self.token_embedding_table(idx)  # Replacing embedding to the indices
        pos_emb = self.position_embedding_table(tf.range(T, dtype=tf.int32)) # (T,C)
        x = token_emb + pos_emb # (B,T,C)
        logits = self.lm_head(x  ) # (B, T, vocab_size)

        if targets is None:
            loss = None
        else:
            # Reshaping the tensor so that it's compatible with categorical cross entropy
            B, T, C = tf.shape(logits) # Get the shape of logits
            logits = tf.reshape(logits, (B * T, C)) # Flatten logits for comparison
            targets = tf.reshape(targets, (B * T,)) # Flatten targets
            loss = tf.reduce_mean(tf.keras.losses.sparse_categorical_crossentropy(targets, logits, from_logits=True))
        return logits, loss

    def generate(self, idx, max_new_tokens):
        '''
        Text generating method
        '''
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :]  # becomes (B, C)
            # apply softmax to get probabilities
            probs = tf.nn.softmax(logits, axis=-1)  # (B, C)
            # sample prediction from the distribution
            idx_next = tf.random.categorical(tf.math.log(probs), num_samples=1, dtype=tf.int64)

#            idx_next = tf.random.categorical(probs, num_samples=1)  # (B, 1)
            # append sampled index to the running sequence
            idx = tf.concat([idx, tf.cast(idx_next, tf.int32)], axis=1)  # (B, T+1)
        return idx

model = BigramLanguageModel(vocab_size)
logits, loss = model.call(xb, yb)
print(logits.shape)
print(loss.numpy())

print(decode(model.generate(idx=tf.zeros((1, 1), dtype=tf.int32), max_new_tokens=100)[0].numpy().tolist()))

(256, 65)
4.175136

sZTe-Wz-K-?hNl?Yr:r'KUFLHH:QmLbpClI
oYwnqePrE
!zgz'U:,?ZgzxEjItgpzAQjGjM$vv.;OBdqFlP qxcwcexWhPKs:$'


In [57]:
# Video from 1:00:00. Need to recheck how self-attention functions

# Version 4: self-attention
tf.random.set_seed(1337)
B,T,C = 4, 8, 32 # batch, time, channels
x = tf.random.normal(shape=(B, T, C))

# Single head perform self-attention
head_size = 16
key = tf.keras.layers.Dense(units=head_size, use_bias=False)
query = tf.keras.layers.Dense(units=head_size, use_bias=False)
value = tf.keras.layers.Dense(units=head_size, use_bias=False)

# All tokens in all positions produce independent key and query
k = key(x) # B, T, 16
q = query(x) # B, T, 16
# Communicating key with query
w = q @ tf.transpose(k, perm=[0,2,1]) # (B, T, 16) @ (B, 16, T) -> (B,T,T)

tril = tf.linalg.band_part(tf.ones((T,T)),num_lower = 8, num_upper= 0)
w = tf.zeros((T,T))
w = tf.where(tril == 0, float('-inf'), w) # Upper triangular masking, indicating future bow cannot communicate with the past
w = tf.nn.softmax(w, axis = -1) # normalizing the weight matrix

v = value(x)
out = w @ v
#out = w @ x # K : private information

out.shape

TensorShape([4, 8, 32])

In [58]:
# Verifying whether the row sum of weights equal 1
import numpy as np
# Convert TensorFlow tensor to NumPy array
w_np = w.numpy()

# Set NumPy print options to suppress scientific notation
np.set_printoptions(suppress=True)

# Print the tensor
print(w_np[0].round(6))

[[ -2.352858  -0.9454     4.500268   1.751455   1.893816   5.342155
   -3.741913   1.551336]
 [ -2.895782   5.46449  -10.862509  -5.067875  -4.580257  -2.239648
    9.104425   7.052182]
 [  1.075756  -0.152148   3.072863  -5.866308   3.787939  -3.551019
    4.57528    1.745807]
 [  4.697159   4.967068   6.319349   4.695271   5.009486   3.592492
    1.927323   4.652435]
 [  5.710098   1.648603   4.232074  -4.275444  -3.463936  -7.252948
    8.692588  -2.965877]
 [  1.453369   0.007635   4.491168  -4.188583   0.833989  -2.208618
    4.399607  -1.450341]
 [ -0.103023   1.397626  -0.395158  -5.729246  -3.42565    2.331519
    7.638572  -0.109329]
 [  4.120043   5.568096  -2.19814    1.586588  -3.767792  -4.173142
    5.310882   6.194066]]
